Algoritmo "23/08/2022"
Var
 t_c:inteiro
 Idade:inteiro
Inicio
    escreval("Informe sua idade: ")
     leia (idade)

    escreval("Quantos anos de contribuição p/ o innss: ")
     leia(t_c)

    se (t_c >=15) e (idade >=65) entao
      escreval("PARABÉNS! Você tem direito a aposentadoria.")
     senao
      escreval("Você ainda não tem direito ao benefício da aposentadoria")
    fimse

Fimalgoritmo

